spring:
    data:
        mongodb:
            # host : mongodb://localhost # host name where mongodb is running
            # port: 27017 #port number, by default MongoDB uses the 27017 port
            # database: catalog #name of the database
            # username: #user name for db
            # password:  # your secret password
            
            user:
            password:
            uri: mongodb://localhost:27017/catalog
            
    application:
        name: Catalog

    profiles:
        active: default

    cloud:
        config:
            uri: http://localhost:8888

        bootstrap:
            enabled: true

server:
    port: 8081

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
