server:
    port: 8084
spring:
    application:
        name : bffshop
    profiles:
        active: default

    datasource:
        url: jdbc:postgresql://localhost:5432/bffshop
        username: postgres
        password: root
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate: 
            ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update

    cloud:
        config:
            enabled: false
            uri: http://localhost:8888
management:
    security:
        enabled: false
    health:
        consul:
            enabled: false
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka